### ISSUE TITLE
migration error against version 0.13

### ISSUE THREAD

**Issue by miladz68** [emartech/kong-plugin-header-based-rate-limiting#1]
hi
thanks for creating this nice plugin for kong. I am trying to use this plugin in kong version 0.13 but cassandra migrations are throwing the following errors.
```
migrating header-based-rate-limiting for keyspace kong
Error: [cassandra error] Error during migration 2018-08-22-153000_init_header_based_rate_limiting: [Invalid] Unknown type kong.integer

```
I would like to know against which version of kong have you tested it ?

**Comment by BlasiusVonSzerencsi** [comment]
Hi,

We've used the plugin in production with v0.13.1 and v0.14.1 of Kong, but internally we have Postgres as the data store and not Cassandra.

We'll look into the issue, thanks for opening it!

**Comment by BlasiusVonSzerencsi** [comment]
I'll have to confirm it, but it looks like that we've got the wrong type there. The Cassandra's equivalent of INTEGER is DECIMAL, COUNTER, etc... (according to http://cassandra.apache.org/doc/4.0/cql/types.html).

Sorry for the issue, I'll update the issue once we have news on the investigation and/or the fix.

**Comment by miladz68** [comment]
@BlasiusVonSzerencsi Thanks for the quick response. I will also look into and try to fix it.

**Comment by miladz68** [comment]
created a pull request  #2

**Comment by BlasiusVonSzerencsi** [comment]
Hi,

Unfortunately, while @SFAriel was getting deeper and deeper into the investigation he realized, that not only the migration is broken, but in one query we used `IS NULL`-s which can cause a runtime failure.

We'll also check whether there is an easy way to fix that issue, and then release a new version.

Thanks again for reaching out and sorry for the issue and the delay.

**Comment by SFAriel** [comment]
Hi @miladz68 ,

Could you please check if the latest release (1.1.0 on luarocks) works under Kong 0.13.x? I just released an updated version that supports Cassandra 3.x, but I haven't tested it beyond getting our test cases green.

We are currently using Kong 0.14.1 with Postgres, but the code doesn't use any new 0.14.x features (like Kong PDK) so I'm hoping it works just fine under 0.13.x. The fix required quite a lot more than the migration using the correct CQL types as we employ some custom DB queries that don't translate well from PostgreSQL to CQL.

**Comment by SFAriel** [comment]
Gonna close this now, but feel free to re-open if the issue persists.
