### ISSUE TITLE
Does the plugin compatible with version 0.31 enterprise?

### ISSUE THREAD

**Issue by EtiNoked** [emartech/kong-plugin-header-based-rate-limiting#3]
Does this plugin work with Kong 0.31 enterprise version?
I've tried to add the configuration but got 400 response from the server

`POST http://host.docker.internal:8001/apis/13bdc1c7-d632-4569-b1a5-57c61e436b32/plugins
  { config:
    { default_rate_limit: 2,
      identification_headers: [ 'authorization' ] },
   name: 'header-based-rate-limiting' }

400 Bad Request { config: 'Plugin "header-based-rate-limiting" not found' }
 Error: Bad Request
 {"config":"Plugin \"header-based-rate-limiting\" not found"}`

**Comment by SFAriel** [comment]
Hi @EtiNoked

Currently the plugin supports Kong CE 0.13.x, which means it requires at least Kong EE 0.32, as the implementation depends on the then newly introduced Services and Routes entities.
